version: '1.0'
networks:
  backend:

services:
  redis:
    image: redis:latest
    container_name: 'docker-redis'
    networks:
      - backend
    volumes:
      - ../redis/redis.conf:/etc/redis/redis.conf:rw
      - ../redis/data:/data
    command: ['redis-server', '/etc/redis/redis.conf']

    ports:
      - 6379:6379

  mysql:
    image: mysql:8.0
    container_name: 'docker-mysql'
    networks:
      - backend
    volumes:
      - ../mysql/config:/etc/mysql/conf.d:rw
      - ../mysql/data:/var/lib/mysql:rw
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=528478huaHUA@
